In [1]:
#1-D
import numpy as np

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
#Finding indexes of minima and maxima:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)

In [7]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [8]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])