In [34]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

C:\Users\User\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [35]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [36]:
train_sample = []
train_label = []
for i in range(1000):
    younger_ages = randint(13, 64)
    train_sample.append(younger_ages)
    train_label.append(0)
    
    older_ages = randint(65, 100)
    train_sample.append(older_ages)
    train_label.append(1)

In [37]:
print(train_sample)

[24, 86, 63, 99, 28, 74, 45, 100, 60, 91, 20, 94, 25, 67, 58, 82, 61, 95, 50, 91, 63, 92, 44, 72, 20, 98, 27, 71, 44, 67, 59, 75, 59, 68, 56, 81, 21, 73, 45, 95, 18, 85, 47, 83, 64, 85, 39, 94, 36, 98, 20, 83, 21, 85, 58, 90, 15, 98, 33, 83, 35, 80, 26, 78, 47, 84, 30, 68, 19, 67, 27, 80, 40, 68, 40, 88, 51, 88, 59, 85, 46, 66, 20, 96, 55, 73, 25, 85, 23, 91, 48, 68, 50, 70, 29, 97, 64, 87, 44, 91, 58, 84, 54, 69, 30, 67, 14, 96, 45, 75, 22, 84, 36, 65, 54, 66, 35, 89, 48, 89, 36, 94, 25, 98, 55, 95, 56, 71, 30, 95, 54, 86, 52, 65, 33, 85, 56, 68, 54, 86, 19, 72, 41, 86, 59, 67, 30, 77, 46, 96, 17, 79, 25, 75, 34, 87, 53, 91, 21, 68, 53, 88, 32, 67, 32, 91, 19, 91, 16, 87, 55, 89, 52, 69, 13, 83, 46, 75, 60, 79, 54, 73, 46, 79, 31, 90, 23, 71, 42, 84, 53, 68, 58, 82, 41, 90, 53, 92, 46, 81, 59, 97, 40, 66, 45, 89, 28, 79, 61, 72, 19, 71, 35, 80, 38, 100, 23, 83, 23, 93, 14, 89, 29, 72, 42, 83, 57, 87, 20, 97, 50, 95, 51, 77, 47, 84, 24, 77, 56, 95, 40, 82, 53, 74, 36, 70, 19, 85, 15, 6

In [38]:
print(train_label)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 

In [39]:
train_sample = np.array(train_sample)
train_label = np.array(train_label)

In [40]:
train_label

array([0, 1, 0, ..., 1, 0, 1])

In [41]:
train_sample

array([24, 86, 63, ..., 98, 62, 66])

In [42]:
scaler = MinMaxScaler(feature_range = (0, 1))
scaler_train_sample = scaler.fit_transform(train_sample.reshape(-1, 1))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [43]:
model = Sequential([Dense(16, input_dim = 1, activation = 'relu'), Dense(32, activation = 'relu'), Dense(2, activation = 'softmax')])

In [44]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [45]:
#we need to compile becuuse it helps to change the weights assign to neurons
model.compile(Adam(lr = 0.001), loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [46]:
model.fit(train_sample, train_label, 10, epochs = 10)

Epoch 1/10
2000/2000 [==============================] - 1s 387us/step - loss: 0.7332 - acc: 0.6050
Epoch 2/10
2000/2000 [==============================] - 0s 175us/step - loss: 0.5136 - acc: 0.7555
Epoch 3/10
2000/2000 [==============================] - 0s 174us/step - loss: 0.4314 - acc: 0.8340
Epoch 4/10
2000/2000 [==============================] - 0s 173us/step - loss: 0.3730 - acc: 0.8700
Epoch 5/10
2000/2000 [==============================] - 0s 178us/step - loss: 0.3069 - acc: 0.9045
Epoch 6/10
2000/2000 [==============================] - 0s 189us/step - loss: 0.2670 - acc: 0.9215
Epoch 7/10
2000/2000 [==============================] - 0s 173us/step - loss: 0.2293 - acc: 0.9390
Epoch 8/10
2000/2000 [==============================] - 0s 174us/step - loss: 0.1981 - acc: 0.9435
Epoch 9/10
2000/2000 [==============================] - 0s 172us/step - loss: 0.1633 - acc: 0.9590
Epoch 10/10
2000/2000 [==============================] - 0s 172us/step - loss: 0.1567 - acc: 0.9530


In [52]:
test_sample = []
test_label = []
for i in range(500):
    younger_ages = randint(13, 64)
    test_sample.append(younger_ages)
    test_label.append(0)
    
    older_ages = randint(65, 100)
    test_sample.append(older_ages)
    test_label.append(1)

test_sample = np.array(train_sample)
test_label = np.array(train_label)   

test_sample_output = model.predict_classes(test_sample, batch_size = 10)

In [54]:
from sklearn.metrics import confusion_matrix
cn = confusion_matrix(test_label, test_sample_output)
cn

array([[ 974,   26],
       [   0, 1000]], dtype=int64)